spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:5432/lovable
    username: postgres
    password: Rishi1062@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    openai:
      api-key:
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-oss-120b:free
          temperature: 0.0


server:
  port : 8081

jwt:
  secret-key: nckscnkfhqweurkhwqkndkqwhroiu1worksankfhasluroiqwekfnskjghjkwerlfydklhS

stripe:
  api:
    secret: sk_test_51T2jjuD8MHp65DgYJquRGDeOoJ7DnSohfoOsElFksnJ47kNhnQFz6cyxDkCi554i2bUBv7y21i8Vih2hC46ceqZS00qLLQF4l7
  webhook:
    secret: whsec_e28cb3b4722bf346dfcee9fa58705030cb991495faa835ef26e17cd5ad4651a6

client:
  url: http://localhost:8081